### ISSUE TITLE
Is this is a game ?

### ISSUE THREAD

**Issue by Thecakeisgit** [Plazmaz/randfiles#1]

**Comment by Plazmaz** [comment]
Nope, this is a honeypot for github dorks. https://github.com/techgaun/github-dorks/blob/master/github-dorks.txt Thank you for visiting the page, confirming that my ip logging system works. I will remove you from the list :)

**Comment by Thecakeisgit** [comment]
It's to trap peoples, to see your repos ? xD

**Comment by Plazmaz** [comment]
The primary function is to track bad actors looking for sensitive files on github. There are many people who fail to use the .gitignore file effectively or simply accidentally upload files. There are also many bots and hackers who attempt to gather this information and use it for malicious purposes
